const LOGIN_USER = "LOGIN_USER";
const LOADING = "LOADING";
const SIGNUP_USER = "SIGNUP_USER";
const ERRORS = "ERRORS";
const LOGOUT_USER = "LOGOUT_USER";
const GET_PROFILE = "GET_PROFILE";
const ASK_QUESTION = "ASK_QUESTION";

export {
  LOGIN_USER, LOADING, SIGNUP_USER, ERRORS, LOGOUT_USER, GET_PROFILE, ASK_QUESTION
}
