const LOGIN_USER = "LOGIN_USER";
const LOADING = "LOADING";
const SIGNUP_USER = "SIGNUP_USER";
const ERRORS = "ERRORS";
const LOGOUT_USER = "LOGOUT_USER";
const GET_PROFILE = "GET_PROFILE";
const ASK_QUESTION = "ASK_QUESTION";
const GET_QUESTIONS = "GET_QUESTIONS";
const SEND_ANSWER = "SEND_ANSWER";
const GET_QUESTION = "GET_QUESTION";
const SEND_COMMENT = "SEND_COMMENT";
const UPVOTE = "UPVOTE";
const DOWNVOTE = "DOWNVOTE";
const UN_UPVOTE = "UN_UPVOTE";
const UN_DOWNVOTE = "UN_DOWNVOTE";
const CHECK = "CHECK";
const UN_CHECK = "UN_CHECK";

export {
  LOGIN_USER, LOADING, SIGNUP_USER, ERRORS, LOGOUT_USER, GET_PROFILE, ASK_QUESTION, GET_QUESTIONS,
  SEND_ANSWER, GET_QUESTION, SEND_COMMENT, UPVOTE, DOWNVOTE, UN_UPVOTE, UN_DOWNVOTE, CHECK, UN_CHECK
}
